name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync

      - name: Run database tests
        run: |
          uv run python -c "from rental_database import rental_db; print(rental_db.get_database_stats())"

      - name: Run import tests
        run: |
          uv run python -c "from main import app; print('✅ App loaded')"
          uv run python -c "import langchain_rental_scraper; print('✅ Scraper loaded')"

      - name: Comment PR
        uses: actions/github-script@v7
        if: success()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Tests passed! Ready for review.'
            })
